#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

mkdir testing

curl -L -o nomic-embed-text-v1.5.gguf --output-dir testing https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF/resolve/main/nomic-embed-text-v1.5.Q2_K.gguf
